apiVersion: v1
kind: Service
metadata:
  name: static-site-service
spec:
  type: NodePort
  selector:
    app: static-website   # Asegúrate de que coincida
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
