apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static-site
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/c/Users/Casa/0311AT-K8S/static-website"
